--- 
- hosts: centos_servers
  tasks: 
  - yum:
     name: git
     state: present
    when: ansible_facts['os_family'] == "Debian"
 # - name: Execute below shell command
  #  shell: echo "Only on redhat 6 and above" 
   # when: [ansible_lsb][major_release] | int >= 6
     #var: ansible_facts['lsb']['major_release']
