---
- name: Modle to copy ansible.cfg file from here to /opt/ folder in ubuntu mahcine
  hosts: ubuntu_servers
  tasks:
  - copy:
     src: ansible.cfg
     dest: /opt/
     owner: ansible
     group: ansible
     mode: '0644'
