---
- name: Copy Module
  hosts: ubuntu_servers
  tasks:
  - copy:
     #src: copy_file
     content: '# This is content testing'
     dest: /home/ansible/content.txt
     owner: ansible
     group: ansible
     mode: '0644'
     backup: yes
