---
- name: Setup MariaDB server on Centos machines
  hosts: centos_servers
  #vars:
   # pymysqlpython: MySQL-python
    #db_user: siva
    #db_password: 12345
   # db_name: accounts
  tasks:
  - name: install maria db server
    yum:
      name: mariadb-server
      state: present
  - name: start and enable maria db
    service:
      name: mariadb
      state: started
      enabled: yes
  - name: Install MySQL-python module
    yum:
      name: "{{pymysqlpython}}" #MySQL-python
      state: present
  - name: Printing user name
    debug:
     msg: "Creating {{db_user}} in Maria db "
  - name: Adds a user in Mysql db
    mysql_user:
      name: "{{db_user}}"
      password: "{{db_password}}" #12345
      priv: '*.*:ALL'
      state: present 
  - name: Create a new database with name 'accounts'
    mysql_db:
      name: "{{db_name}}"
      state: present
